@server=http://localhost:8080
get {{server}}

### create app
post {{server}}/apps
Content-Type: application/json

{
  "name": "docs",
  "type": "static"
}

### update domain. of the app

patch {{server}}/apps/37QOAhsBYPJaGqXsdbAMYNWEKuL/domain

{
  "domain": "docs.localhost",
  "path_prefix": "/"
}

### register user
post {{server}}/auth/register
Content-Type: application/json

{
  "username": "testuserwi",
  "password": "testpasS@87&89"
}


### login user
post {{server}}/auth/login
Content-Type: application/json

{
  "username": "passup",
  "password": "Pass@123"
}


### log out
post {{server}}/auth/logout
Content-Type: application/json
