@server=http://localhost:8080
get {{server}}

### create app
post {{server}}/apps
Content-Type: application/json

{
  "name": "newapp",
  "type": "dynamic"
}


### register user
post {{server}}/auth/register
Content-Type: application/json

{
  "username": "testuserwi",
  "password": "testpasS@87&89"
}


### login user
post {{server}}/auth/login
Content-Type: application/json

{
  "username": "passup",
  "password": "Pass@123"
}


### log out
post {{server}}/auth/logout
Content-Type: application/json
