name: zipup
services:
  valkey:
    image: valkey/valkey:7-alpine
    container_name: valkey
    restart: unless-stopped
    networks:
      core_network: {}
      wireguard_network:
        ipv4_address: 172.25.0.3
    volumes:
      - valkey_data:/data
    command: ["valkey-server", "--appendonly", "yes"]
    labels:
      - app_type=system
      - app_name=valkey
    logging:
      driver: none

  openresty:
    build:
      context: ./openresty
      dockerfile: Dockerfile
    container_name: openresty
    ports:
      - "8080:8080"
    volumes:
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./openresty/lua:/lua:ro
      # - ./config:/config:ro
      - static_artifacts:/static_artifacts
    networks:
      - edge_network
    restart: unless-stopped
    depends_on:
      - zipup
    labels:
      - app_type=system
      - app_name=openresty
    logging:
      driver: none

  zipup:
    image: node:24-bookworm-slim
    working_dir: /app
    container_name: zipup
    networks:
      - edge_network
      - core_network
      - wireguard_network
    restart: unless-stopped
    user: root
    volumes:
      # - /app/node_modules
      - zipup_data:/data
      - ./wireguard/wg0.conf:/etc/wireguard/wg0.conf

      - static_artifacts:/static_artifacts
      - dynamic_artifacts:/dynamic_artifacts
      - secrets:/secrets
      - /var/run/docker.sock:/var/run/docker.sock
    # command: sh -c "npm install -g pnpm && pnpm install && pnpm --filter backend run dev"
    # environment:
    #   - NODE_ENV=development
    # ports:
    #   - "3000:8080"
    labels:
      - app_type=system
      - app_name=zipup
    depends_on:
      - vector
      - wireguard

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    networks:
      core_network: {}
      wireguard_network:
        ipv4_address: 172.25.0.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: zipup
      POSTGRES_USER: zipup
      POSTGRES_PASSWORD: zipup

    labels:
      - app_type=system
      - app_name=postgres

  vector:
    image: timberio/vector:0.38.X-alpine
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
    ports:
      - "8686:8686"
    depends_on:
      - victorialogs
    user: root
    labels:
      - app_type=system
      - app_name=vector

  victorialogs:
    image: victoriametrics/victoria-logs:latest
    container_name: victorialogs
    # ports:
    #   - "9428:9428"
    command:
      - "--storageDataPath=/vlogs"
    volumes:
      - vldata:/vlogs
    labels:
      - app_type=system
      - app_name=victorialogs
    logging:
      driver: none
    networks:
      core_network: {}
      wireguard_network:
        ipv4_address: 172.25.0.4

  wireguard:
    image: cmulk/wireguard-docker:alpine
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WATCH_CHANGES=1
    volumes:
      # - wireguard_config:/etc/wireguard
      - ./wireguard/wg0.conf:/etc/wireguard/wg0.conf
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      core_network: {}
      wireguard_network:
        ipv4_address: 172.25.0.5
    labels:
      - app_type=system
      - app_name=wireguard
volumes:
  vldata:
  zipup_data:
  valkey_data:
  static_artifacts:
  dynamic_artifacts:
  secrets:
  postgres_data:
  wireguard_config:

networks:
  edge_network:
    driver: bridge
  core_network:
    driver: bridge
  wireguard_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24