name: zipup
services:
  valkey:
    image: valkey/valkey:8.1-alpine3.23
    container_name: valkey
    restart: unless-stopped
    networks:
      core_network: {}
      wireguard_network:
        ipv4_address: 172.25.0.3
    volumes:
      - valkey_data:/data
      - ./users.acl:/usr/local/etc/redis/users.acl
    command:
      [
        "valkey-server",
        "--appendonly",
        "yes",
        "--aclfile",
        "/usr/local/etc/redis/users.acl",
      ]
    labels:
      - appType=system
      - appName=valkey
    logging:
      driver: none

  openresty:
    build:
      context: ./openresty
      dockerfile: Dockerfile
    container_name: openresty
    environment:
      - ACME_EMAIL=${ACME_EMAIL:?ACME_EMAIL is required in .env}
    volumes:
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./openresty/lua:/lua:ro
      - ./certs:/etc/openresty:ro
      # - ./config:/config:ro
      - static_artifacts:/static_artifacts
    networks:
      - edge_network
    restart: unless-stopped
    depends_on:
      - zipup
    labels:
      - appType=system
      - appName=openresty
    logging:
      driver: json-file
      options:
        labels: "appName,appType"

  zipup:
    working_dir: /app
    container_name: zipup
    networks:
      - edge_network
      - core_network
      - wireguard_network
    restart: unless-stopped
    user: root
    volumes:
      - ./wireguard/wg0.conf:/etc/wireguard/wg0.conf

      - static_artifacts:/static_artifacts
      - dynamic_artifacts:/dynamic_artifacts
      - secrets:/secrets
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - appType=system
      - appName=zipup
    depends_on:
      - vector
      - wireguard
    logging:
      driver: json-file
      options:
        labels: "appName,appType"

  postgres:
    image: postgres:17-bookworm
    container_name: postgres
    restart: unless-stopped
    logging:
      driver: none
    networks:
      core_network: {}
      wireguard_network:
        ipv4_address: 172.25.0.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: zipup
      POSTGRES_PASSWORD: zipup

    labels:
      - appType=system
      - appName=postgres

  vector:
    image: timberio/vector:0.38.X-alpine
    container_name: vector
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
    networks:
      core_network: {}
    ports:
      - "8686:8686"
    depends_on:
      - victorialogs
    user: root
    labels:
      - appType=system
      - appName=vector

  victorialogs:
    image: victoriametrics/victoria-logs:v1.48.0
    container_name: victorialogs
    # ports:
    #   - "9428:9428"
    command:
      - "--storageDataPath=/vlogs"
    volumes:
      - vldata:/vlogs
    labels:
      - appType=system
      - appName=victorialogs
    logging:
      driver: none
    networks:
      core_network: {}
      wireguard_network:
        ipv4_address: 172.25.0.4

  wireguard:
    image: ghcr.io/ankitaabad/zipup-wireguard:latest
    container_name: wireguard
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WATCH_CHANGES=1
    volumes:
      # - wireguard_config:/etc/wireguard
      - ./wireguard/wg0.conf:/etc/wireguard/wg0.conf
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      core_network: {}
      wireguard_network:
        ipv4_address: 172.25.0.5
    labels:
      - appType=system
      - appName=wireguard
    logging:
      driver: json-file
      options:
        labels: "appName,appType"
volumes:
  vldata:
  zipup_data:
  valkey_data:
  static_artifacts:
  dynamic_artifacts:
  secrets:
  postgres_data:
  wireguard_config:

networks:
  edge_network:
    driver: bridge
  core_network:
    driver: bridge
  wireguard_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
