# version: "3.8"
name: zipup
services:
  valkey:
    image: valkey/valkey:7-alpine
    container_name: valkey
    restart: unless-stopped
    networks:
      - core_network
      - wireguard_network
    volumes:
      - valkey_data:/data
    command: ["valkey-server", "--appendonly", "yes"]
    labels:
      - app_type=system
      - app_name=valkey
    logging:
      driver: none

  openresty:
    build:
      context: ./openresty
      dockerfile: Dockerfile
    container_name: openresty
    ports:
      - "8080:8080"
    volumes:
      - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./openresty/lua:/lua:ro
      - ./config:/config:ro
      - static_artifacts:/static_artifacts

      # - ./sites:/data/sites:ro
    networks:
      - edge_network
    restart: unless-stopped
    depends_on:
      - zipup
    labels:
      - app_type=system
      - app_name=openresty
    logging:
        driver: none

  zipup:
    image: node:24-bookworm-slim
    working_dir: /app
    container_name: zipup
    networks:
      - edge_network
      - core_network
      - wireguard_network
    restart: unless-stopped
    user: root
    volumes:
      - ./:/app # <-- mount CURRENT directory
      - /app/node_modules
      # - ./config:/config
      - zipup_data:/data
      - wireguard_config:/config
      - static_artifacts:/static_artifacts
      - dynamic_artifacts:/dynamic_artifacts
      - secrets:/secrets
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "npm install -g pnpm && pnpm install  && pnpm --filter backend run dev"
    environment:
      - NODE_ENV=development
    ports:
      - "3000:8080"
    labels:
      - app_type=system
      - app_name=zipup
    logging:
      driver: "json-file"
      options:
        labels: "app_name"  
    # logging:
    #   driver: "none"   # disable default Docker logging → Vector will handle logs
    depends_on:
      - vector
      - wireguard
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    networks:
      - core_network
      - wireguard_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: zipup
      POSTGRES_USER: zipup
      POSTGRES_PASSWORD: zipup
    ports:
      - "5432:5432"
      
    labels:
      - app_type=system
      - app_name=postgres
  vector:
    image: timberio/vector:0.38.X-alpine
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
    ports:
      - "8686:8686" # Vector internal API (optional)
    depends_on:
      - victorialogs
    user: root
    labels:
      - app_type=system
      - app_name=vector
    
  victorialogs:
    image: victoriametrics/victoria-logs:latest
    container_name: victorialogs
    ports:
      - "9428:9428" # VictoriaLogs HTTP ingestion + query
    command:
      - "--storageDataPath=/vlogs"
    volumes:
      - vldata:/vlogs
    labels:
      - app_type=system
      - app_name=victorialogs
    logging:
        driver: none        
    networks:
      - core_network
      - wireguard_network          
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - SERVERPORT=51820
      - LOG_CONFS=false
      - PEERS=5
      - ALLOWEDIPS=10.13.13.0/24
      # - POSTUP=iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      # - POSTDOWN=iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

    volumes:
      - wireguard_config:/config
      - /lib/modules:/lib/modules
      - ./wireguard-startup.sh:/etc/wireguard-startup.sh
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - wireguard_network
    labels:
      - app_type=system
      - app_name=wireguard    
    entrypoint: ["/bin/bash", "/etc/wireguard-startup.sh"]
volumes:
  vldata:
  zipup_data:
  valkey_data:
  static_artifacts:
  dynamic_artifacts:
  secrets:
  postgres_data:
  wireguard_config:
networks:
  edge_network:
    driver: bridge
  core_network:
    driver: bridge
  wireguard_network:
    driver: bridge