
services:


  zipup:

    volumes:
      - ./app:/app:ro
    command: ["node", "/app/backend/dist/index.js"]
    environment:
      - NODE_ENV=production
      - FRONTEND_DIST_DIR=/app/frontend/dist
