services:

  openresty:
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENV=production     
  zipup:
    image: ghcr.io/ankitaabad/zipup:${ZIPUP_VERSION:-latest}
    ports:
      - "127.0.0.1:3000:8080"
    volumes:
      - ./db:/db
    environment:
      - NODE_ENV=production
      - FRONTEND_DIST_DIR=/app/frontend/dist
      - DB_PATH=/db
