[Interface]
Address = 10.13.13.2/24
PrivateKey = mJ1MFu2wpu4wUBKRUr5bxCMp4ECYiFFqBXQ6yxytAGo=
ListenPort = 51820
[Peer]
PublicKey = B7bOz6VNoNLnHQmY2hbXeWnaoMa9Va2r37u/niB0hXM=
PresharedKey = 8osMVAb0kFq5200PZjvA2TMhoFz0bpuRLYC6TWdsfqY=
Endpoint = 127.0.0.1:51820
AllowedIPs = 172.25.0.0/24
PersistentKeepalive = 25