[Interface]
PrivateKey = sBwiL7UePLdGA55b9TNwnRsfwpNo5ZNtqWoqfq8Y3Xs=
Address = 10.13.13.1/24
ListenPort = 51820

PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;iptables -t nat -A PREROUTING -i %i -p tcp --dport 5432 -j DNAT --to-destination 172.25.0.2:5432
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE;iptables -t nat -D PREROUTING -i %i -p tcp --dport 5432 -j DNAT --to-destination 172.25.0.2:5432
[Peer]
# local
PublicKey = N2esCD79RoDlvWdw4SA7ECOK2drwGxL0nxQZ7NrnkCI=
PresharedKey = busF6IINsh3Bbm5Nb7NNsjnAO4YNItJpIcxzokWaLSg=
AllowedIPs = 10.13.13.2/32
PersistentKeepalive = 25

