[Interface]
PrivateKey = yKRXENCJwQApuILDesRWZxnLMKAIRQifOQlMQauRs30=
Address = 10.13.13.1/24
ListenPort = 51820

PostUp = iptables -A FORWARD -i %i -j ACCEPT
PostUp = iptables -A FORWARD -o %i -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostUp = iptables -t nat -A PREROUTING -i %i -p tcp --dport 5432 -j DNAT --to-destination 172.25.0.2:5432
PostUp = iptables -t nat -A PREROUTING -i %i -p tcp --dport 6379 -j DNAT --to-destination 172.25.0.3:6379
PostUp = iptables -t nat -A PREROUTING -i %i -p tcp --dport 9428 -j DNAT --to-destination 172.25.0.4:9428
PostDown = iptables -D FORWARD -i %i -j ACCEPT
PostDown = iptables -D FORWARD -o %i -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -t nat -D PREROUTING -i %i -p tcp --dport 5432 -j DNAT --to-destination 172.25.0.2:5432
PostDown = iptables -t nat -D PREROUTING -i %i -p tcp --dport 6379 -j DNAT --to-destination 172.25.0.3:6379
PostDown = iptables -t nat -D PREROUTING -i %i -p tcp --dport 9428 -j DNAT --to-destination 172.25.0.4:9428
[Peer]
# test
PublicKey = cTcsMGcTAxM3o+nTH3goxTlBdu/QUTIArnx1ZwaLdDY=
PresharedKey = v4b71AxUArdKnFZIeY7v5X/SGLoHV5cFJOVrGg6uiWQ=
AllowedIPs = 10.13.13.2/32
PersistentKeepalive = 25

