[Interface]
PrivateKey = UKc7D5K+MNbcYm9etmG8Y8lFsKknOSHFHilTbmCMK34=
Address = 10.13.13.1/24
ListenPort = 51820

PostUp = iptables -A FORWARD -i %i -j ACCEPT; \
         iptables -A FORWARD -o %i -j ACCEPT; \
         iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE; \
         iptables -t nat -A POSTROUTING -o br+ -j MASQUERADE

PostDown = iptables -D FORWARD -i %i -j ACCEPT; \
           iptables -D FORWARD -o %i -j ACCEPT; \
           iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE; \
           iptables -t nat -D POSTROUTING -o br+ -j MASQUERADE
